---
- hosts: aws
  become: true
  tasks:
  # enable EPEL repo by installing the epel-release package
    - name: install EPEL repo
      become: yes
      yum: 
        name: epel-release 
        state: present

    - name: ensure nginx is at the latest version
      yum: name=nginx state=latest
    - name: start nginx
      service:
          name: nginx
          state: started
